stages:
  - build
  - test
  - deploy

build:
  script:
    - composer install
    - bin/console cache:clear
  stage: build
  only:
    - master
  allow_failure: false

deploy_production:
  script:
    - cap production deploy --trace
  stage: deploy
  only:
    - master
  allow_failure: false