# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
      api_exception_subscriber:
            class: AppBundle\EventListener\ApiExceptionSubscriber
            arguments: ["%kernel.debug%"]
            tags:
                - { name: kernel.event_subscriber }

      jwt_token_authenticator:
            class: AppBundle\Security\JwtTokenAuthenticator
            autowire: true

      aws_factory:
            class: AppBundle\Service\AWSClientFactory
            arguments:
                - "%aws_version%"
                - "%aws_region%"
                - "%aws_key%"
                - "%aws_secret%"
