# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository}'

    AppBundle\Controller\:
            resource: '../../src/AppBundle/Controller'
            public: true
            tags: ['controller.service_arguments']

    AppBundle\Queue\SQS:
        arguments: ["@aws.sqs"]
        public: true

    AppBundle\Messaging\ConfirmationEmail:
        arguments: ['@mailer']
        public: true

    AppBundle\Messaging\Mailchimp:
        arguments: ['@mailer']
        public: true

    AppBundle\Service\CacheFactory:
        arguments: ['@service_container']
        public: true

    AppBundle\Worker:
        public: true

    AppBundle\Factory\CommandFactory:
        arguments: ['@serializer']
        public: true

    AppBundle\Factory\CacheFactory:
        public: true

    AppBundle\Queue\SignUpCompletedSubscriber:
        arguments: ['@serializer', '@AppBundle\Queue\SQS']

