# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
      aws.factory:
            class: AppBundle\Service\Aws\AWSClientFactory
            arguments:
                - "%aws_version%"
                - "%aws_region%"
                - "%aws_key%"
                - "%aws_secret%"
      aws.sns.helper:
            class: AppBundle\Service\Aws\SNS
            arguments: ["@=service('aws.factory').create('sns')"]

      aws.sqs.helper:
            class: AppBundle\Service\Aws\SQS
            arguments: ["@=service('aws.factory').create('sqs')"]

      processor.confirmation.email:
            class: AppBundle\Messaging\ConfirmationEmailProcessor
            arguments: ['@mailer']

      processor.mailchimp:
            class: AppBundle\Messaging\MailchimpProcessor
            arguments: ['@mailer']

      messenger:
            class: AppBundle\Service\Messenger
            arguments: ['@aws.sqs.helper']