# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository}'

    AppBundle\Service\Aws\SQS:
        arguments: ["@aws.sqs"]
        public: true

    AppBundle\Messaging\ConfirmationEmail:
        arguments: ['@mailer']
        public: true

    AppBundle\Messaging\Mailchimp:
        arguments: ['@mailer']
        public: true

    AppBundle\Service\CacheFactory:
        arguments: ['@service_container']
        public: true

    AppBundle\Service\Worker:
        public: true

    AppBundle\Factory\CommandFactory:
        arguments: ['@serializer']
        public: true

    AppBundle\Factory\CacheFactory:
        public: true

    command_handler_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        tags: ['container.service_locator']
        arguments:
            -
                AppBundle\Model\ConfirmationEmail: '@AppBundle\Handler\ConfirmationEmailHandler'
                AppBundle\Model\Mailchimp: '@AppBundle\Handler\MailchimpHandler'

    AppBundle\CommandBus\CommandBus:
        arguments: ["@command_handler_locator"]
        public: true