# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
      jwt_token_authenticator:
            class: AppBundle\Security\JwtTokenAuthenticator
            autowire: true