version: 2
jobs:
    build:
        timezone:
            Australia/Melbourne
        docker:
            - image: circleci/php:7.1-fpm
        steps:
            - checkout
            - run: composer self-update
            - run: composer install
            - deploy:
                command: |
                      if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        bundle exec cap production deploy --trace
                      fi