version: 2
jobs:
    build:
        timezone:
            Australia/Melbourne
        docker:
            - image: circleci/php:7.1.8-browsers
        steps:
            - checkout
            - run: sudo apt-get install rubygems
            - run: sudo gem install bundler
            - run: sudo bundler install
            - run: composer self-update
            - run: composer install -n --prefer-dist
            - deploy:
                command: |
                      if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        bundle exec cap production deploy --trace
                      fi