version: 2
jobs:
    build:
        timezone:
            Australia/Melbourne
        docker:
            - image: circleci/php:7.2-browsers-legacy
        steps:
            - checkout
            - run: sudo composer self-update
            - run: composer install -n --prefer-dist
    deploy:
        working_directory: ~/integration
        docker:
            - image: ansible/ansible:ubuntu1604
              environment:
                  ANSIBLE_HOST_KEY_CHECKING: no
        steps:
            - run:
                name: Install System Packages
                command: pip install --upgrade pip & pip install ansible
            - checkout
            - restore_cache:
                key: integration-{{ .Branch }}-{{ checksum "./ansible/requirements.yml" }}-v1
            - run: ansible-galaxy install -r ansible/requirements.yml
            - save_cache:
                key: integration-{{ .Branch }}-{{ checksum "./ansible/requirements.yml" }}-v1
                paths:
                    - "./root/.ansible/roles"


            - run: echo $ANSIBLE_VAULT_PASS > ./ansible/.vault-pass.txt
            - run: ansible-playbook ansible/deploy.yml -i ansible/hosts.ini --vault-password-file=./ansible/.vault-pass.txt
            - run: rm ./ansible/.vault-pass.txt

workflows:
    version: 2
    build_deploy:
        jobs:
            - build:
                filters:
                    branches:
                        only: master
            - deploy:
                filters:
                    branches:
                        only: master
                requires:
                    - build