version: 2
jobs:
    build:
        timezone:
            Australia/Melbourne
        docker:
            - image: circleci/php:7.1.8-browsers
        steps:
            - checkout
            - run: sudo composer self-update
            - run: composer install -n --prefer-dist